apiVersion: v1
kind: Service
metadata:
  labels:
    app: cip-nginx-server-dep
  name: cip-nginx-server-dep
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-server
  type: ClusterIP
